#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

# test and try building backend
cd back
npm run lint --max-warnings=0 || exit 1
npm run build || exit 1
npm run test || exit 1
rm -r build

# run linter on frontend
cd ../front
npm run lint -- --max-warnings=72 || exit 1
npm run build || exit 1