version: '3.2'
services:
  blockchain:
    build:
      context: ./
      dockerfile: ./docker/blockchain.Dockerfile
    container_name: blockchain
    ports:
      - "8545:8545"
    volumes:
      - .:/user/src/app
    entrypoint: /usr/src/app/blockchain/run.sh

  localstack:
    build:
      context: ./docker
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,ses
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - './.aws:/root/.aws'
      - '/var/run/docker.sock:/var/run/docker.sock'
      -
  localstack-settings:
    build:
      context: ./docker
    depends_on:
      - localstack
    image: localstack/localstack:latest
    volumes:
      - './.localstack:/tmp/localstack'
      - './.aws:/root/.aws'
      - '/var/run/docker.sock:/var/run/docker.sock'
    entrypoint: >
      sh -c '
      sleep 10 &&
      echo "SETUP CREDENTIALS" &&
      echo "localstack\nlocalstack\neu-west-1\njson\n" | aws configure --profile localstack &&
      echo "STARTING VERIFY EMAIL" &&
      aws ses verify-email-identity
      --email-address no-reply@strongnode.io
      --region eu-west-1
      --profile localstack
      --endpoint-url=http://localstack:4566'