version: '3.2'
services:
  blockchain:
    build:
      context: ./
      dockerfile: ./docker/blockchain.Dockerfile
    container_name: blockchain
    ports:
      - "8545:8545"
    volumes:
      - .:/usr/src/app
    entrypoint: /usr/src/app/blockchain/run.sh

  localstack:
    build:
      context: ./docker
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,ses,rekognition
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - './.aws:/root/.aws'
      - '/var/run/docker.sock:/var/run/docker.sock'
  localstack-settings:
    build:
      context: ./docker
    depends_on:
      - localstack
    image: localstack/localstack:latest
    volumes:
      - './.localstack:/tmp/localstack'
      - './.aws:/root/.aws'
      - '/var/run/docker.sock:/var/run/docker.sock'
    entrypoint: >
      sh -c '
      sleep 10 &&
      echo "SETUP CREDENTIALS" &&
      echo "localstack\nlocalstack\neu-west-1\njson\n" | aws configure --profile localstack &&
      echo "STARTING VERIFY EMAIL" &&
      aws ses verify-email-identity
      --email-address no-reply@strongnode.io
      --region eu-west-1
      --profile localstack
      --endpoint-url=http://localstack:4566'
  limiter-service:
    container_name: limiter
    image: rust:1.61.0
    working_dir: '/app'
    volumes:
      - ./limiter-service:/app
      - limiter-target-cache:/app/target
      - limiter-cargo-cache:/usr/local/cargo/registry
    entrypoint: /app/entrypoint.sh
    ports:
      - 3012:3012

volumes:
  limiter-target-cache:
  limiter-cargo-cache:
