const swaggerAutogen = require('swagger-autogen')()

const doc = {
  info: {
    version: '', // by default: '1.0.0'
    title: 'Autogenerated REST API SNE Dashboard', // by default: 'REST API'
    description: '' // by default: ''
  }
}

const outputFile = './swagger_output.json'
const endpointsFiles = [
  './src/app/routes/auth.routes.ts',
  './src/app/routes/cryptocurrency.routes.js',
  './src/app/routes/user.routes.ts'
]

swaggerAutogen(outputFile, endpointsFiles, doc)
