[package]
name = "limiter-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "0.9.2"
dashmap = "5.3.4"
dotenv = "0.15.0"
env_logger = "0.9.0"